name: deep-audio
channels:
  - conda-forge
dependencies:
  - seaborn
  - python=3.11
  - torchvision
  - ipykernel
  - pytorch[version='>=2.4']
  - pyarrow>=14
  - torchaudio
  - scikit-learn
  - pip
  - python-dotenv
  - librosa
  - jupyter
  - ffmpeg
  - pandas
  - scipy
  - matplotlib
  - libsndfile
  - lightning
  - evaluate
  - transformers
  - datasets>=2.16
  - kagglehub
  - pip:
      - phonemizer
      - focalcodec@git+https://github.com/lucadellalib/focalcodec.git@main
